/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_tsinghua_lumaqq_hotkey_KeyBinder */

#ifndef _Included_edu_tsinghua_lumaqq_hotkey_KeyBinder
#define _Included_edu_tsinghua_lumaqq_hotkey_KeyBinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_tsinghua_lumaqq_hotkey_KeyBinder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_tsinghua_lumaqq_hotkey_KeyBinder_init
  (JNIEnv *, jobject);

/*
 * Class:     edu_tsinghua_lumaqq_hotkey_KeyBinder
 * Method:    bind
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_tsinghua_lumaqq_hotkey_KeyBinder_bind
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_tsinghua_lumaqq_hotkey_KeyBinder
 * Method:    unbind
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_tsinghua_lumaqq_hotkey_KeyBinder_unbind
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
